import { buildNumberedConversationChunks, parseConversationMessages, type ParsedConversationMessage } from "./conversation";
import { getRuntimeProviderConfig, type RuntimeProviderConfig } from "./provider-config";
import type { AnalysisModule, BuyingDriver, CommunicationImprovement, CommunicationTrait, DealBlocker, EmotionEvidence, EmotionTurningPoint, KnowledgeScriptReference, NextStepStrategy, ProductMention, Provider } from "./types";

export type BlockerAssessment = Pick<DealBlocker, "evidenceMessageId" | "handlingStatus" | "salesEvidenceMessageId" | "salesEvidenceQuote" | "salesEvidenceTranslation" | "resolutionEvidenceMessageId" | "resolutionEvidenceQuote" | "resolutionEvidenceTranslation" | "solutionDirection">;

export type AtomicAnalysisResult =
  | { summary: string; confidence: number }
  | { profile: string[]; confidence: number }
  | { productMentions: ProductMention[] }
  | { currentState: string; currentStateEvidence: EmotionEvidence[]; confidence: number }
  | { emotionTurningPoints: EmotionTurningPoint[] }
  | { personalitySummary: string; personalityTraits: CommunicationTrait[] }
  | { decisionStyle: string; decisionFactors: string[]; decisionPace: string; communicationApproach: string; decisionEvidence: EmotionEvidence[]; confidence: number }
  | { motivationLevel: "强" | "中" | "弱"; readiness: "高" | "中" | "低"; buyingDrivers: BuyingDriver[] }
  | { biggestBlocker: string; priorityTask: string; blockers: DealBlocker[] }
  | { blockerAssessments: BlockerAssessment[] }
  | { improvements: CommunicationImprovement[] }
  | { nextStrategy: NextStepStrategy }
  | { suggestedReply: string; suggestedReplyTranslation: string; knowledgeReferenceIds: string[]; knowledgeReferences?: KnowledgeScriptReference[] };

const evidenceSchema = { type: "object", additionalProperties: false, required: ["messageId", "quote", "translation", "interpretation"], properties: { messageId: { type: "string" }, quote: { type: "string" }, translation: { type: "string" }, interpretation: { type: "string" } } };
const productSchema = { type: "object", additionalProperties: false, required: ["name", "mentionedBy", "customerAwareness", "customerInterest", "awarenessReason", "evidenceMessageId", "evidenceQuote"], properties: { name: { type: "string" }, mentionedBy: { type: "string", enum: ["客户", "销售", "双方"] }, customerAwareness: { type: "string", enum: ["不了解", "初步了解", "有使用经验", "明确熟悉", "无法判断"] }, customerInterest: { type: "string", enum: ["明确感兴趣", "可能感兴趣", "未表现兴趣", "明确拒绝", "无法判断"] }, awarenessReason: { type: "string" }, evidenceMessageId: { type: "string" }, evidenceQuote: { type: "string" } } };
const driverSchema = { type: "object", additionalProperties: false, required: ["title", "desiredOutcome", "painOrExpectation", "strength", "purchaseIntent", "conversionReason", "evidenceMessageId", "evidenceQuote", "evidenceTranslation"], properties: { title: { type: "string" }, desiredOutcome: { type: "string" }, painOrExpectation: { type: "string" }, strength: { type: "string", enum: ["强", "中", "弱"] }, purchaseIntent: { type: "string", enum: ["明确", "较高", "观察中"] }, conversionReason: { type: "string" }, evidenceMessageId: { type: "string" }, evidenceQuote: { type: "string" }, evidenceTranslation: { type: "string" } } };
const blockerBaseProperties = { title: { type: "string" }, category: { type: "string", enum: ["产品匹配", "产品知识", "价格与预算", "质量与COA", "公司与供应商信任", "包装与交付", "物流清关与时效", "支付与资金安全", "决策时机", "内部审批", "其他顾虑"] }, concern: { type: "string" }, dealImpact: { type: "string" }, evidenceMessageId: { type: "string" }, evidenceQuote: { type: "string" }, evidenceTranslation: { type: "string" } };
const improvementSchema = { type: "object", additionalProperties: false, required: ["title", "priority", "issue", "customerEvidenceMessageId", "customerEvidenceQuote", "customerEvidenceTranslation", "handling", "salesEvidenceMessageId", "salesEvidenceQuote", "salesEvidenceTranslation", "recommendation"], properties: { title: { type: "string" }, priority: { type: "string", enum: ["高", "中", "低"] }, issue: { type: "string" }, customerEvidenceMessageId: { type: "string" }, customerEvidenceQuote: { type: "string" }, customerEvidenceTranslation: { type: "string" }, handling: { type: "string" }, salesEvidenceMessageId: { type: "string" }, salesEvidenceQuote: { type: "string" }, salesEvidenceTranslation: { type: "string" }, recommendation: { type: "string" } } };

const schemas: Record<AnalysisModule, Record<string, unknown>> = {
  summary: { type: "object", additionalProperties: false, required: ["summary", "confidence"], properties: { summary: { type: "string" }, confidence: { type: "number", minimum: 0, maximum: 1 } } },
  profile: { type: "object", additionalProperties: false, required: ["profile", "confidence"], properties: { profile: { type: "array", items: { type: "string" } }, confidence: { type: "number", minimum: 0, maximum: 1 } } },
  products: { type: "object", additionalProperties: false, required: ["productMentions"], properties: { productMentions: { type: "array", items: productSchema } } },
  emotion_state: { type: "object", additionalProperties: false, required: ["currentState", "currentStateEvidence", "confidence"], properties: { currentState: { type: "string" }, currentStateEvidence: { type: "array", maxItems: 3, items: evidenceSchema }, confidence: { type: "number", minimum: 0, maximum: 1 } } },
  emotion_trend: { type: "object", additionalProperties: false, required: ["emotionTurningPoints"], properties: { emotionTurningPoints: { type: "array", maxItems: 8, items: { type: "object", additionalProperties: false, required: ["messageId", "quote", "translation", "interpretation", "label", "score", "reason"], properties: { ...evidenceSchema.properties, label: { type: "string" }, score: { type: "number", minimum: -2, maximum: 2 }, reason: { type: "string" } } } } } },
  personality: { type: "object", additionalProperties: false, required: ["personalitySummary", "personalityTraits"], properties: { personalitySummary: { type: "string" }, personalityTraits: { type: "array", maxItems: 5, items: { type: "object", additionalProperties: false, required: ["trait", "explanation", "evidence"], properties: { trait: { type: "string" }, explanation: { type: "string" }, evidence: { type: "array", maxItems: 3, items: evidenceSchema } } } } } },
  decision: { type: "object", additionalProperties: false, required: ["decisionStyle", "decisionFactors", "decisionPace", "communicationApproach", "decisionEvidence", "confidence"], properties: { decisionStyle: { type: "string" }, decisionFactors: { type: "array", maxItems: 5, items: { type: "string" } }, decisionPace: { type: "string" }, communicationApproach: { type: "string" }, decisionEvidence: { type: "array", maxItems: 4, items: evidenceSchema }, confidence: { type: "number", minimum: 0, maximum: 1 } } },
  drivers: { type: "object", additionalProperties: false, required: ["motivationLevel", "readiness", "buyingDrivers"], properties: { motivationLevel: { type: "string", enum: ["强", "中", "弱"] }, readiness: { type: "string", enum: ["高", "中", "低"] }, buyingDrivers: { type: "array", maxItems: 3, items: driverSchema } } },
  blockers: { type: "object", additionalProperties: false, required: ["biggestBlocker", "priorityTask", "blockers"], properties: { biggestBlocker: { type: "string" }, priorityTask: { type: "string" }, blockers: { type: "array", maxItems: 8, items: { type: "object", additionalProperties: false, required: ["title", "category", "concern", "dealImpact", "evidenceMessageId", "evidenceQuote", "evidenceTranslation"], properties: blockerBaseProperties } } } },
  blocker_status: { type: "object", additionalProperties: false, required: ["blockerAssessments"], properties: { blockerAssessments: { type: "array", maxItems: 8, items: { type: "object", additionalProperties: false, required: ["evidenceMessageId", "handlingStatus", "salesEvidenceMessageId", "salesEvidenceQuote", "salesEvidenceTranslation", "resolutionEvidenceMessageId", "resolutionEvidenceQuote", "resolutionEvidenceTranslation", "solutionDirection"], properties: { evidenceMessageId: { type: "string" }, handlingStatus: { type: "string", enum: ["未解决", "已回答-客户未追问", "客户明确认可"] }, salesEvidenceMessageId: { type: "string" }, salesEvidenceQuote: { type: "string" }, salesEvidenceTranslation: { type: "string" }, resolutionEvidenceMessageId: { type: "string" }, resolutionEvidenceQuote: { type: "string" }, resolutionEvidenceTranslation: { type: "string" }, solutionDirection: { type: "string" } } } } } },
  improvements: { type: "object", additionalProperties: false, required: ["improvements"], properties: { improvements: { type: "array", maxItems: 6, items: improvementSchema } } },
  strategy: { type: "object", additionalProperties: false, required: ["nextStrategy"], properties: { nextStrategy: { type: "object", additionalProperties: false, required: ["strategySummary", "primaryGoal", "reasoning", "actions", "communicationMethod", "avoidActions", "evidence"], properties: { strategySummary: { type: "string" }, primaryGoal: { type: "string" }, reasoning: { type: "string" }, actions: { type: "array", minItems: 1, maxItems: 5, items: { type: "string" } }, communicationMethod: { type: "string" }, avoidActions: { type: "array", maxItems: 4, items: { type: "string" } }, evidence: { type: "array", maxItems: 5, items: evidenceSchema } } } } },
  reply: { type: "object", additionalProperties: false, required: ["suggestedReply", "suggestedReplyTranslation", "knowledgeReferenceIds"], properties: { suggestedReply: { type: "string" }, suggestedReplyTranslation: { type: "string" }, knowledgeReferenceIds: { type: "array", items: { type: "string" } } } },
};

const common = `你是严谨的 B2B 销售对话分析师。每条消息都有稳定编号 M00001。只依据本次对话，不得虚构、拼接或改写原文；判断与事实分开，不确定就明确说明。所有分析字段使用中文。只完成当前这一个原子任务，不补做其他板块。`;
const prompts: Record<AnalysisModule, string> = {
  summary: "概括客户需求、销售已做事项、当前进展和未决问题。不要输出画像、阶段或行动建议。",
  profile: "自由提炼 5-12 个具体、可独立阅读的客户画像标签，覆盖有证据的身份经验、需求关注、信任价格、决策与沟通特征；不设固定分类，不凑数。",
  products: "列出对话提及的每个具体产品、药物或多肽并去重。公司、厂家和店铺名不是产品。客户没有回应销售提及的产品时，了解和兴趣必须为无法判断。每项引用包含产品名或直接证明了解程度的原文。",
  emotion_state: "只判断客户当前情绪与可观察心理状态，引用最近且直接的客户原文。不得做疾病或人格障碍诊断。",
  emotion_trend: "按消息顺序提取 0-8 个真正发生的情绪转折并说明原因，score 只能为 -2 到 2；没有明显变化返回空数组。",
  personality: "只分析聊天中可观察到的沟通性格倾向，用一句话综合，再列具体倾向及各自客户原文；不输出敏感点、MBTI 或防御模式。",
  decision: "只分析客户的决策方式、考虑因素、节奏和适合的沟通方式，每个核心判断必须由客户原文支持。",
  drivers: "只识别真正推动客户下单的核心驱动力，最多3项。需求、结果、痛点和购买意向的近义表达必须合并。客户尚未解决的疑问不能当作驱动力。",
  blockers: "只发现可能阻碍成交的明确问题：产品疑问、价格预算、质量COA、信任、包装交付、物流、支付、时机或审批。语义相同只保留一项，每项必须引用客户逐字原文。此任务不判断销售是否解决。",
  blocker_status: "独立通读完整聊天，找出每个客户阻力原文，并按消息顺序判断销售处理状态。没有正面回答或客户再次追问=未解决；销售回答后客户未追问=已回答-客户未追问；销售回答后客户明确认可=客户明确认可。礼貌致谢、沉默和换话题不算认可。evidenceMessageId 必须是阻力客户消息编号。",
  improvements: "评估本次销售沟通质量，最多6项，按高、中、低排序。每项三段：issue 说明发生了什么及影响；handling 客观总结销售如何处理，未处理写销售尚未处理；recommendation 说明应该怎样处理。不重复罗列客户阻力，不生成完整回复。不得仅因缺少医疗免责声明或未建议咨询医生而生成问题。",
  strategy: "根据上游结果生成唯一的下一步成交策略。必须综合总结、沟通性格、决策方式、核心下单驱动力、成交阻力及其处理状态、沟通不足。给出一个核心目标、原因、1-5步顺序、沟通方式和暂时不要做的事，不得机械复述板块。",
  reply: "根据上游策略生成一段可直接发送的自然回复，沿用客户语言；同时返回自然简体中文核对。不得读取、引用或模仿话术库内容；knowledgeReferenceIds 固定返回空数组。",
};

function parseJson<T>(text: string): T {
  const clean = text.trim().replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "");
  const start = clean.indexOf("{"); const end = clean.lastIndexOf("}");
  return JSON.parse(start >= 0 && end > start ? clean.slice(start, end + 1) : clean) as T;
}

function validateRaw(module: AnalysisModule, value: unknown) {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("根结果不是 JSON 对象");
  const raw = value as Record<string, unknown>;
  const required = schemas[module].required as string[];
  const missing = required.filter((key) => raw[key] === undefined || raw[key] === null);
  if (missing.length) throw new Error(`缺少字段：${missing.join("、")}`);
  if (module === "summary" && (typeof raw.summary !== "string" || !raw.summary.trim())) throw new Error("对话总结为空");
  if (module === "profile" && !Array.isArray(raw.profile)) throw new Error("客户画像不是数组");
  if (module === "products" && !Array.isArray(raw.productMentions)) throw new Error("产品识别结果不是数组");
  if (module === "emotion_state" && (!Array.isArray(raw.currentStateEvidence) || typeof raw.currentState !== "string")) throw new Error("当前情绪字段不完整");
  if (module === "emotion_trend" && !Array.isArray(raw.emotionTurningPoints)) throw new Error("情绪变化不是数组");
  if (module === "personality" && !Array.isArray(raw.personalityTraits)) throw new Error("沟通性格字段不完整");
  if (module === "decision" && (!Array.isArray(raw.decisionFactors) || !Array.isArray(raw.decisionEvidence))) throw new Error("决策方式字段不完整");
  if (module === "drivers" && !Array.isArray(raw.buyingDrivers)) throw new Error("下单驱动力不是数组");
  if (module === "blockers" && !Array.isArray(raw.blockers)) throw new Error("成交阻力不是数组");
  if (module === "blocker_status" && !Array.isArray(raw.blockerAssessments)) throw new Error("阻力状态不是数组");
  if (module === "improvements" && !Array.isArray(raw.improvements)) throw new Error("沟通改善结果不是数组");
  if (module === "strategy") { const strategy = raw.nextStrategy as Record<string, unknown> | undefined; if (!strategy || !Array.isArray(strategy.actions) || !strategy.actions.length) throw new Error("下一步策略字段不完整"); }
  if (module === "reply" && (typeof raw.suggestedReply !== "string" || !raw.suggestedReply.trim() || typeof raw.suggestedReplyTranslation !== "string" || !raw.suggestedReplyTranslation.trim())) throw new Error("建议回复字段不完整");
}

async function requestJson(config: RuntimeProviderConfig, provider: Provider, module: AnalysisModule, input: string, extra = ""): Promise<unknown> {
  const instruction = `${common}\n${prompts[module]}${extra}\n严格按 JSON Schema 输出单个合法 JSON 对象，不输出 Markdown。没有内容的数组返回 []，没有证据的字符串返回空字符串。\nJSON Schema:\n${JSON.stringify(schemas[module])}`;
  let lastError = "未知错误";
  for (let attempt = 0; attempt < 2; attempt += 1) {
    try {
      if (provider === "openai") {
        const response = await fetch(`${config.baseUrl || "https://api.openai.com"}/v1/responses`, { method: "POST", headers: { Authorization: `Bearer ${config.apiKey}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: config.model, instructions: attempt ? `${instruction}\n上次输出无效，请完整重做。` : instruction, input, store: false, text: { format: { type: "json_schema", name: `clientlens_${module}`, strict: true, schema: schemas[module] } } }), signal: AbortSignal.timeout(90_000) });
        if (!response.ok) throw new Error(`OpenAI request failed: ${response.status}`);
        const payload = await response.json() as { output_text?: string; output?: Array<{ content?: Array<{ type?: string; text?: string }> }> };
        const text = payload.output_text || payload.output?.flatMap((item) => item.content || []).find((item) => item.type === "output_text")?.text || "";
        const result = parseJson(text);
        validateRaw(module, result);
        return result;
      }
      const messages = [{ role: "system", content: instruction }, { role: "user", content: input }, ...(attempt ? [{ role: "user", content: `上次输出无效：${lastError}。请重新输出完整合法 JSON。` }] : [])];
      const response = await fetch(`${config.baseUrl || "https://api.deepseek.com"}/chat/completions`, { method: "POST", headers: { Authorization: `Bearer ${config.apiKey}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: config.model, messages, response_format: { type: "json_object" }, thinking: { type: "disabled" }, temperature: 0.1, max_tokens: 2800 }), signal: AbortSignal.timeout(90_000) });
      if (!response.ok) throw new Error(`DeepSeek request failed: ${response.status}`);
      const payload = await response.json() as { choices?: Array<{ message?: { content?: string | null } }> };
      const result = parseJson(payload.choices?.[0]?.message?.content || "");
      validateRaw(module, result);
      return result;
    } catch (error) { lastError = error instanceof Error ? error.message : "无效 JSON"; }
  }
  throw new Error(`${module} 模块连续两次返回无效结果：${lastError}`);
}

function normalized(value: string) { return value.normalize("NFKC").replace(/[‘’]/g, "'").replace(/[–—]/g, "-").replace(/^[\s"'“”]+|[\s"'“”]+$/g, "").replace(/\s+/g, " ").toLowerCase(); }
function verified(messages: Map<string, ParsedConversationMessage>, id: string, quote: string, role?: "customer" | "sales") { const message = messages.get(id); if (!message || (role && message.role !== role)) return false; const q = normalized(quote).replace(/^(customer|sales|客户|销售)\s*:\s*/i, ""); const m = normalized(message.content); return q.length >= 4 && (m.includes(q) || q.includes(m)); }
function strings(value: unknown, fallback: string[] = []) { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string" && Boolean(item.trim())).map((item) => item.trim()) : fallback; }
function confidence(value: unknown, fallback = 0.3) { const number = Number(value); return Number.isFinite(number) ? Math.max(0, Math.min(1, number)) : fallback; }

function evidenceList(value: unknown, messages: ParsedConversationMessage[], limit = 5): EmotionEvidence[] { const map = new Map(messages.map((message) => [message.id, message])); return (Array.isArray(value) ? value : []).flatMap((candidate) => { if (!candidate || typeof candidate !== "object") return []; const item = candidate as Record<string, unknown>; const id = typeof item.messageId === "string" ? item.messageId : ""; const quote = typeof item.quote === "string" ? item.quote : ""; if (!verified(map, id, quote, "customer")) return []; return [{ messageId: id, quote, translation: typeof item.translation === "string" ? item.translation.trim() : "", interpretation: typeof item.interpretation === "string" ? item.interpretation.trim() : "" }]; }).filter((item) => item.interpretation).slice(0, limit); }

function normalizeResult(module: AnalysisModule, value: unknown, messages: ParsedConversationMessage[]): AtomicAnalysisResult {
  const raw = value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
  const map = new Map(messages.map((message) => [message.id, message]));
  if (module === "summary") return { summary: typeof raw.summary === "string" && raw.summary.trim() ? raw.summary.trim() : "当前对话信息不足。", confidence: confidence(raw.confidence) };
  if (module === "profile") return { profile: strings(raw.profile).slice(0, 15), confidence: confidence(raw.confidence) };
  if (module === "products") { const productMentions: ProductMention[] = (Array.isArray(raw.productMentions) ? raw.productMentions : []).flatMap((candidate): ProductMention[] => { if (!candidate || typeof candidate !== "object") return []; const item = candidate as Record<string, unknown>; const id = String(item.evidenceMessageId || ""); const quote = String(item.evidenceQuote || ""); const name = String(item.name || "").trim(); if (!name || !verified(map, id, quote)) return []; const message = map.get(id)!; const mentionedBy: ProductMention["mentionedBy"] = item.mentionedBy === "双方" || item.mentionedBy === "客户" || item.mentionedBy === "销售" ? item.mentionedBy : message.role === "customer" ? "客户" : "销售"; const customerAwareness: ProductMention["customerAwareness"] = item.customerAwareness === "不了解" || item.customerAwareness === "初步了解" || item.customerAwareness === "有使用经验" || item.customerAwareness === "明确熟悉" ? item.customerAwareness : "无法判断"; const customerInterest: ProductMention["customerInterest"] = item.customerInterest === "明确感兴趣" || item.customerInterest === "可能感兴趣" || item.customerInterest === "未表现兴趣" || item.customerInterest === "明确拒绝" ? item.customerInterest : "无法判断"; return [{ name, mentionedBy, customerAwareness, customerInterest, awarenessReason: String(item.awarenessReason || "").trim(), evidenceMessageId: id, evidenceQuote: quote }]; }).filter((item, index, all) => all.findIndex((other) => other.name.toLowerCase() === item.name.toLowerCase()) === index); return { productMentions }; }
  if (module === "emotion_state") return { currentState: String(raw.currentState || "信息不足，暂无法判断当前情绪和心理状态").trim(), currentStateEvidence: evidenceList(raw.currentStateEvidence, messages, 3), confidence: confidence(raw.confidence) };
  if (module === "emotion_trend") { const emotionTurningPoints = (Array.isArray(raw.emotionTurningPoints) ? raw.emotionTurningPoints : []).flatMap((candidate) => { if (!candidate || typeof candidate !== "object") return []; const item = candidate as Record<string, unknown>; const evidence = evidenceList([item], messages, 1)[0]; if (!evidence) return []; const score = Number(item.score); return [{ ...evidence, label: String(item.label || "情绪变化").trim(), score: Number.isFinite(score) ? Math.max(-2, Math.min(2, score)) : 0, reason: String(item.reason || evidence.interpretation).trim() }]; }); return { emotionTurningPoints }; }
  if (module === "personality") { const personalityTraits = (Array.isArray(raw.personalityTraits) ? raw.personalityTraits : []).flatMap((candidate) => { if (!candidate || typeof candidate !== "object") return []; const item = candidate as Record<string, unknown>; const trait = String(item.trait || "").trim(); const explanation = String(item.explanation || "").trim(); const evidence = evidenceList(item.evidence, messages, 3); return trait && explanation && evidence.length ? [{ trait, explanation, evidence }] : []; }).slice(0, 5); return { personalitySummary: String(raw.personalitySummary || "信息不足，暂无法判断沟通性格倾向").trim(), personalityTraits }; }
  if (module === "decision") return { decisionStyle: String(raw.decisionStyle || "信息不足，暂无法判断决策方式").trim(), decisionFactors: strings(raw.decisionFactors).slice(0, 5), decisionPace: String(raw.decisionPace || "信息不足").trim(), communicationApproach: String(raw.communicationApproach || "保持清晰、直接，并逐项核实需求。").trim(), decisionEvidence: evidenceList(raw.decisionEvidence, messages, 4), confidence: confidence(raw.confidence) };
  if (module === "drivers") { const buyingDrivers: BuyingDriver[] = (Array.isArray(raw.buyingDrivers) ? raw.buyingDrivers : []).flatMap((candidate): BuyingDriver[] => { if (!candidate || typeof candidate !== "object") return []; const item = candidate as Record<string, unknown>; const id = String(item.evidenceMessageId || ""); const quote = String(item.evidenceQuote || ""); if (!String(item.title || "").trim() || !verified(map, id, quote, "customer")) return []; const strength: BuyingDriver["strength"] = item.strength === "强" || item.strength === "弱" ? item.strength : "中"; const purchaseIntent: BuyingDriver["purchaseIntent"] = item.purchaseIntent === "明确" || item.purchaseIntent === "较高" ? item.purchaseIntent : "观察中"; return [{ title: String(item.title).trim(), desiredOutcome: String(item.desiredOutcome || "").trim(), painOrExpectation: String(item.painOrExpectation || "").trim(), strength, purchaseIntent, conversionReason: String(item.conversionReason || "").trim(), evidenceMessageId: id, evidenceQuote: quote, evidenceTranslation: String(item.evidenceTranslation || "").trim() }]; }).slice(0, 3); return { motivationLevel: raw.motivationLevel === "强" || raw.motivationLevel === "中" ? raw.motivationLevel : "弱", readiness: raw.readiness === "高" || raw.readiness === "中" ? raw.readiness : "低", buyingDrivers }; }
  if (module === "blockers") { const blockers = (Array.isArray(raw.blockers) ? raw.blockers : []).flatMap((candidate) => { if (!candidate || typeof candidate !== "object") return []; const item = candidate as Record<string, unknown>; const id = String(item.evidenceMessageId || ""); const quote = String(item.evidenceQuote || ""); const title = String(item.title || "").trim(); if (!title || !verified(map, id, quote, "customer")) return []; const categories = ["产品匹配", "产品知识", "价格与预算", "质量与COA", "公司与供应商信任", "包装与交付", "物流清关与时效", "支付与资金安全", "决策时机", "内部审批"] as const; return [{ title, category: categories.includes(item.category as typeof categories[number]) ? item.category as typeof categories[number] : "其他顾虑" as const, concern: String(item.concern || "").trim(), dealImpact: String(item.dealImpact || "").trim(), evidenceMessageId: id, evidenceQuote: quote, evidenceTranslation: String(item.evidenceTranslation || "").trim(), handlingStatus: "未解决" as const, salesEvidenceMessageId: "", salesEvidenceQuote: "", salesEvidenceTranslation: "", resolutionEvidenceMessageId: "", resolutionEvidenceQuote: "", resolutionEvidenceTranslation: "", solutionDirection: "待结合销售后续处理判断。" }]; }).filter((item, index, all) => all.findIndex((other) => other.evidenceMessageId === item.evidenceMessageId || other.title === item.title) === index).slice(0, 8); return { biggestBlocker: String(raw.biggestBlocker || blockers[0]?.title || "暂未识别明确成交阻力").trim(), priorityTask: String(raw.priorityTask || (blockers[0] ? `优先处理：${blockers[0].title}` : "继续确认客户需求")).trim(), blockers }; }
  if (module === "blocker_status") { const blockerAssessments = (Array.isArray(raw.blockerAssessments) ? raw.blockerAssessments : []).flatMap((candidate) => { if (!candidate || typeof candidate !== "object") return []; const item = candidate as Record<string, unknown>; const issueId = String(item.evidenceMessageId || ""); const issueIndex = messages.findIndex((message) => message.id === issueId && message.role === "customer"); if (issueIndex < 0) return []; let status: DealBlocker["handlingStatus"] = item.handlingStatus === "客户明确认可" || item.handlingStatus === "已回答-客户未追问" ? item.handlingStatus : "未解决"; const salesId = String(item.salesEvidenceMessageId || ""); const salesQuote = String(item.salesEvidenceQuote || ""); const salesIndex = messages.findIndex((message) => message.id === salesId); const resolutionId = String(item.resolutionEvidenceMessageId || ""); const resolutionQuote = String(item.resolutionEvidenceQuote || ""); const resolutionIndex = messages.findIndex((message) => message.id === resolutionId); if (status !== "未解决" && (salesIndex <= issueIndex || !verified(map, salesId, salesQuote, "sales"))) status = "未解决"; if (status === "客户明确认可" && (resolutionIndex <= salesIndex || !verified(map, resolutionId, resolutionQuote, "customer"))) status = "已回答-客户未追问"; return [{ evidenceMessageId: issueId, handlingStatus: status, salesEvidenceMessageId: status === "未解决" ? "" : salesId, salesEvidenceQuote: status === "未解决" ? "" : salesQuote, salesEvidenceTranslation: status === "未解决" ? "" : String(item.salesEvidenceTranslation || "").trim(), resolutionEvidenceMessageId: status === "客户明确认可" ? resolutionId : "", resolutionEvidenceQuote: status === "客户明确认可" ? resolutionQuote : "", resolutionEvidenceTranslation: status === "客户明确认可" ? String(item.resolutionEvidenceTranslation || "").trim() : "", solutionDirection: String(item.solutionDirection || "优先直接回应客户尚未解决的问题。").trim() }]; }); return { blockerAssessments }; }
  if (module === "improvements") { const rank: Record<CommunicationImprovement["priority"], number> = { 高: 0, 中: 1, 低: 2 }; const improvements: CommunicationImprovement[] = (Array.isArray(raw.improvements) ? raw.improvements : []).flatMap((candidate): CommunicationImprovement[] => { if (!candidate || typeof candidate !== "object") return []; const item = candidate as Record<string, unknown>; const title = String(item.title || "").trim(); const issue = String(item.issue || "").trim(); const recommendation = String(item.recommendation || "").trim(); const customerId = String(item.customerEvidenceMessageId || ""); const customerQuote = String(item.customerEvidenceQuote || ""); const salesId = String(item.salesEvidenceMessageId || ""); const salesQuote = String(item.salesEvidenceQuote || ""); if (!title || !issue || !recommendation || (customerId && !verified(map, customerId, customerQuote, "customer")) || (salesId && !verified(map, salesId, salesQuote, "sales"))) return []; const priority: CommunicationImprovement["priority"] = item.priority === "高" || item.priority === "低" ? item.priority : "中"; return [{ title, priority, issue, customerEvidenceMessageId: customerId, customerEvidenceQuote: customerQuote, customerEvidenceTranslation: String(item.customerEvidenceTranslation || "").trim(), handling: String(item.handling || "销售尚未处理").trim(), salesEvidenceMessageId: salesId, salesEvidenceQuote: salesQuote, salesEvidenceTranslation: String(item.salesEvidenceTranslation || "").trim(), recommendation }]; }).sort((a, b) => rank[a.priority] - rank[b.priority]).slice(0, 6); return { improvements }; }
  if (module === "strategy") { const strategy = raw.nextStrategy && typeof raw.nextStrategy === "object" ? raw.nextStrategy as Record<string, unknown> : {}; return { nextStrategy: { strategySummary: String(strategy.strategySummary || "围绕当前最大成交阻力推进一个明确下一步。").trim(), primaryGoal: String(strategy.primaryGoal || "解决最关键成交阻力").trim(), reasoning: String(strategy.reasoning || "结合客户决策方式和真实需求降低不确定性。").trim(), actions: strings(strategy.actions, ["直接处理客户当前最关心的问题。"]).slice(0, 5), communicationMethod: String(strategy.communicationMethod || "表达清晰、节奏克制，每次推进一个目标。").trim(), avoidActions: strings(strategy.avoidActions).slice(0, 4), evidence: evidenceList(strategy.evidence, messages, 5) } }; }
  return { suggestedReply: String(raw.suggestedReply || "").trim(), suggestedReplyTranslation: String(raw.suggestedReplyTranslation || "").trim(), knowledgeReferenceIds: strings(raw.knowledgeReferenceIds) };
}

function combine(module: AnalysisModule, results: AtomicAnalysisResult[], messages: ParsedConversationMessage[]): AtomicAnalysisResult {
  if (results.length === 1) return results[0];
  if (module === "summary") { const items = results as Array<{ summary: string; confidence: number }>; return { summary: items.map((item) => item.summary).filter(Boolean).join("\n"), confidence: Math.min(...items.map((item) => item.confidence)) }; }
  if (module === "profile") { const items = results as Array<{ profile: string[]; confidence: number }>; return { profile: [...new Set(items.flatMap((item) => item.profile))].slice(0, 15), confidence: Math.min(...items.map((item) => item.confidence)) }; }
  if (module === "products") return { productMentions: (results as Array<{ productMentions: ProductMention[] }>).flatMap((item) => item.productMentions).filter((item, index, all) => all.findIndex((other) => other.name.toLowerCase() === item.name.toLowerCase()) === index) };
  if (module === "emotion_state") return results.at(-1)!;
  if (module === "emotion_trend") { const order = new Map(messages.map((message, index) => [message.id, index])); return { emotionTurningPoints: (results as Array<{ emotionTurningPoints: EmotionTurningPoint[] }>).flatMap((item) => item.emotionTurningPoints).filter((item, index, all) => all.findIndex((other) => other.messageId === item.messageId) === index).sort((a, b) => (order.get(a.messageId) || 0) - (order.get(b.messageId) || 0)).slice(0, 8) }; }
  if (module === "personality") { const items = results as Array<{ personalitySummary: string; personalityTraits: CommunicationTrait[] }>; return { personalitySummary: items.map((item) => item.personalitySummary).filter(Boolean).join("；"), personalityTraits: items.flatMap((item) => item.personalityTraits).filter((item, index, all) => all.findIndex((other) => other.trait === item.trait) === index).slice(0, 5) }; }
  if (module === "decision") { const items = results as Array<{ decisionStyle: string; decisionFactors: string[]; decisionPace: string; communicationApproach: string; decisionEvidence: EmotionEvidence[]; confidence: number }>; const best = [...items].sort((a, b) => b.confidence - a.confidence)[0]; return { ...best, decisionFactors: [...new Set(items.flatMap((item) => item.decisionFactors))].slice(0, 5), decisionEvidence: items.flatMap((item) => item.decisionEvidence).filter((item, index, all) => all.findIndex((other) => other.messageId === item.messageId) === index).slice(0, 4), confidence: Math.min(...items.map((item) => item.confidence)) }; }
  if (module === "drivers") { const items = results as Array<{ motivationLevel: "强" | "中" | "弱"; readiness: "高" | "中" | "低"; buyingDrivers: BuyingDriver[] }>; const rank = { 弱: 0, 中: 1, 强: 2 }; const ready = { 低: 0, 中: 1, 高: 2 }; return { motivationLevel: items.sort((a, b) => rank[b.motivationLevel] - rank[a.motivationLevel])[0].motivationLevel, readiness: items.sort((a, b) => ready[b.readiness] - ready[a.readiness])[0].readiness, buyingDrivers: items.flatMap((item) => item.buyingDrivers).filter((item, index, all) => all.findIndex((other) => other.evidenceMessageId === item.evidenceMessageId || other.title === item.title) === index).slice(0, 3) }; }
  if (module === "blockers") { const items = results as Array<{ biggestBlocker: string; priorityTask: string; blockers: DealBlocker[] }>; const blockers = items.flatMap((item) => item.blockers).filter((item, index, all) => all.findIndex((other) => other.evidenceMessageId === item.evidenceMessageId || other.title === item.title) === index).slice(0, 8); return { biggestBlocker: blockers[0]?.title || items[0]?.biggestBlocker || "暂未识别明确成交阻力", priorityTask: items.find((item) => item.priorityTask)?.priorityTask || "继续确认客户需求", blockers }; }
  if (module === "blocker_status") return { blockerAssessments: (results as Array<{ blockerAssessments: BlockerAssessment[] }>).flatMap((item) => item.blockerAssessments).filter((item, index, all) => all.findIndex((other) => other.evidenceMessageId === item.evidenceMessageId) === index) };
  if (module === "improvements") { const rank = { 高: 0, 中: 1, 低: 2 }; return { improvements: (results as Array<{ improvements: CommunicationImprovement[] }>).flatMap((item) => item.improvements).filter((item, index, all) => all.findIndex((other) => other.title === item.title) === index).sort((a, b) => rank[a.priority] - rank[b.priority]).slice(0, 6) }; }
  return results.at(-1)!;
}

export async function analyzeAtomicModuleWithProvider(provider: Provider, conversation: string, module: AnalysisModule, analysisContext?: unknown): Promise<AtomicAnalysisResult | null> {
  const config = await getRuntimeProviderConfig(provider);
  if (!config) return null;
  const messages = parseConversationMessages(conversation);
  const dependent = module === "strategy" || module === "reply";
  const upstream = analysisContext ? `\n\n上游分析结果（只用于综合，不得覆盖原始聊天）：\n${JSON.stringify(analysisContext)}` : "";
  const chunks = buildNumberedConversationChunks(conversation);
  const inputs = dependent ? [chunks.join("\n") + upstream] : chunks;
  const rawResults = await Promise.all(inputs.map((input) => requestJson(config, provider, module, input, "")));
  const normalizedResults = rawResults.map((result) => normalizeResult(module, result, messages));
  const result = combine(module, normalizedResults, messages);
  if (module !== "reply") return result;
  const reply = result as Extract<AtomicAnalysisResult, { suggestedReply: string }>;
  if (!reply.suggestedReply || !reply.suggestedReplyTranslation) throw new Error("建议回复模块字段不完整");
  return { ...reply, knowledgeReferenceIds: [], knowledgeReferences: [] };
}
